services:
  app:
    image: rjournaler-web-app:${IMAGE_TAG:-1.0.2}
    pull_policy: never
    container_name: rjournaler_web_app
    working_dir: /var/www/html
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  worker:
    image: rjournaler-web-worker:${IMAGE_TAG:-1.0.2}
    pull_policy: never
    container_name: rjournaler_web_worker
    working_dir: /app
    env_file:
      - .env
    command: python python/worker/main.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
