-- Data Correlation Engine core schema and indexes.

CREATE TABLE IF NOT EXISTS correlation_period_runs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    period_type ENUM('month','quarter','year') NOT NULL,
    period_year SMALLINT UNSIGNED NOT NULL,
    period_value TINYINT UNSIGNED NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    status ENUM('pending','queued','processing','completed','failed') NOT NULL DEFAULT 'pending',
    source_entry_count INT UNSIGNED NOT NULL DEFAULT 0,
    source_max_entry_updated_at DATETIME NULL,
    generated_at DATETIME NULL,
    last_job_id BIGINT UNSIGNED NULL,
    error_message VARCHAR(500) NULL,
    generated_payload_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_correlation_period (period_type, period_year, period_value),
    INDEX idx_correlation_period_status (status, updated_at),
    INDEX idx_correlation_period_date (period_start, period_end)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS correlation_graph_panels (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    period_run_id BIGINT UNSIGNED NOT NULL,
    panel_key VARCHAR(64) NOT NULL,
    panel_title VARCHAR(255) NOT NULL,
    chart_type VARCHAR(32) NOT NULL,
    panel_payload_json JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_correlation_graph_panels_run FOREIGN KEY (period_run_id) REFERENCES correlation_period_runs(id) ON DELETE CASCADE,
    UNIQUE KEY uq_correlation_graph_panel (period_run_id, panel_key),
    INDEX idx_correlation_graph_panel_key (panel_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS correlation_summaries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    period_run_id BIGINT UNSIGNED NOT NULL,
    summary_type ENUM('psychological','cognitive','executive') NOT NULL,
    generated_text LONGTEXT NOT NULL,
    active_text LONGTEXT NOT NULL,
    source_model VARCHAR(128) NULL,
    generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    edited_by_user_id BIGINT UNSIGNED NULL,
    edited_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_correlation_summaries_run FOREIGN KEY (period_run_id) REFERENCES correlation_period_runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_correlation_summaries_editor FOREIGN KEY (edited_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY uq_correlation_summary_type (period_run_id, summary_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS correlation_custom_definitions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    definition_name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NULL,
    definition_json JSON NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 100,
    created_by_user_id BIGINT UNSIGNED NULL,
    updated_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_correlation_definition_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_correlation_definition_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE KEY uq_correlation_definition_name (definition_name),
    INDEX idx_correlation_definition_active_order (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO correlation_custom_definitions (
    definition_name,
    description,
    definition_json,
    is_active,
    sort_order,
    created_by_user_id,
    updated_by_user_id,
    created_at,
    updated_at
)
SELECT
    'baseline_core_factors',
    'Initial correlation factors from the Correlation Engine work plan',
    JSON_OBJECT(
        'factors', JSON_ARRAY(
            'weather_patterns',
            'days_of_week',
            'time_of_month',
            'emotional_state',
            'sentiment',
            'word_count',
            'thought_fragmentation',
            'named_entities',
            'personality_profile_summary'
        ),
        'notes', 'Generated by migration 016 for baseline correlation coverage.'
    ),
    1,
    10,
    NULL,
    NULL,
    UTC_TIMESTAMP(),
    UTC_TIMESTAMP()
WHERE NOT EXISTS (
    SELECT 1
    FROM correlation_custom_definitions
    WHERE definition_name = 'baseline_core_factors'
);

CREATE INDEX idx_worker_jobs_correlation_queue
ON worker_jobs (job_type, status, run_after, priority);
